uv run --no-sync python -m scripts.grpo_train \
    --model-name /root/autodl-tmp/models/OLMo-2-0425-1B \
    --prompt-path cs336_alignment/prompts/r1_zero.prompt \
    --train-path data/gsm8k/train.jsonl \
    --validation-path data/gsm8k/test.jsonl \
    --num-rollout-steps 50 \
    --rollout-batch-size 256 \
    --group-size 8 \
    --gradient-accumulation-steps 32 \
    --learning-rate 1e-5 \
    --max-grad-norm 1.0 \
    --temperature 1.0 \
    --max-tokens 512 \
    --eval-every 10 \
    --log-rollout-every 40 \
    --n-validation-samples 1024 \
    --seed 0 \
    --training-device cuda:0 \
    --vllm-gpu 1
